" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vim_runtime/my_configs.vim

set runtimepath+=~/.vim_runtime
"set runtimepath+=~/.vim_runtime/my_plugins/vim-go

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim
try
  source ~/.vim_runtime/my_configs.vim
catch
endtry

set nu

" 启用 vim-go 的调试功能
let g:go_debug_enabled = 1


" 保存并格式化 Go 文件
"nnoremap <leader>f :w<CR>:GoFmt<CR>
" 运行当前文件
"nnoremap <leader>r :GoRun<CR>
" 编译当前文件
"nnoremap <leader>c :GoBuild<CR>
" 执行当前包的测试
"nnoremap <leader>t :GoTest<CR>
" 跳转到定义处
nnoremap <leader>d :GoDef<CR>
" 列出引用
nnoremap <leader>r :GoReferrers<CR>
" 查看当前光标下变量的类型信息
nnoremap <leader>i :GoInfo<CR>
" 查找实现接口的类型
nnoremap <leader>gi :GoImplements<CR>
" 列出调用该函数的位置
nnoremap <leader>c :GoCallers<CR>
